language: objective-c
osx_image: xcode8.3

before_install:
# Used to allow pushing to CocoaPods only after all matrixed builds have succeeded
    - npm install --save-dev travis-after-all

xcode_workspace: UnrarKit.xcworkspace

matrix:
  include:
      # The CLANG arguments and find command fail the build on analyzer errors
    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme UnrarKit -sdk macosx -configuration Release analyze test CLANG_ANALYZER_OUTPUT=html CLANG_ANALYZER_OUTPUT_DIR=analyzer-output && [[ -z `find analyzer-output -name "*.html"` ]]
      env: Name=Mac

      # The CLANG arguments and find command fail the build on analyzer errors
    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme "UnrarKit iOS" -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' -configuration Release analyze test CLANG_ANALYZER_OUTPUT=html CLANG_ANALYZER_OUTPUT_DIR=analyzer-output && [[ -z `find analyzer-output -name "*.html"` ]]
      env: Name=iOS

      # The CLANG arguments and find command fail the build on analyzer errors
    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme UnrarExample -sdk iphonesimulator -configuration Release analyze CLANG_ANALYZER_OUTPUT=html CLANG_ANALYZER_OUTPUT_DIR=analyzer-output && [[ -z `find analyzer-output -name "*.html"` ]]
      env: Name=ExampleAppBuild

    - script: ./Scripts/cocoapod-validate.sh
      env: Name=CocoaPods

    - script: ./Scripts/carthage-validate.sh
      env: Name=Carthage

#script:
  # Calling via script until a bug in travis_wait is fixed: https://github.com/travis-ci/travis-ci/issues/7020
#  - travis_wait 15 Scripts/build.sh

after_script:
  - ./Scripts/push-output.sh

# Turn on Docker, container-based infrastructure
sudo: false
