# blocklist
branches:
  except:
  - multivolume

language: objective-c
osx_image: xcode8.2

before_install:
# Used to allow pushing to CocoaPods only after all matrixed builds have succeeded
    - npm install --save-dev travis-after-all

xcode_workspace: UnrarKit.xcworkspace

matrix:
  include:
    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme UnrarKit -sdk macosx -configuration Release analyze test
      env: Name=Mac

    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme "UnrarKit iOS" -destination 'platform=iOS Simulator,id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12,OS=latest' -configuration Release analyze test
      env: Name=iOS

    - script: xcodebuild -workspace UnrarKit.xcworkspace -scheme UnrarExample -sdk iphonesimulator -configuration Release analyze
      env: Name=ExampleAppBuild

    - script: ./Scripts/cocoapod-validate.sh
      env: Name=CocoaPods

    - script: ./Scripts/carthage-validate.sh
      env: Name=Carthage

#script:
  # Calling via script until a bug in travis_wait is fixed: https://github.com/travis-ci/travis-ci/issues/7020
#  - travis_wait 15 Scripts/build.sh

after_script:
  - ./Scripts/push-output.sh

# Turn on Docker, container-based infrastructure
sudo: false
